### PR TITLE
[SC-728] Task: Remove Function mintIssuanceTokenTo() from the Bonding Curves

### PR DESCRIPTION
**Pull request by 0xNuggan**
See rationale in the linear issue.

## What has been done
- Removed mintIssuanceTokenTo() function from contracts, interfaces and tests
- Updated FM_BC_Restricted.... description test, closing issue [SC-727]

### CODE REVIEW

**Review by Zitzak — CHANGES_REQUESTED** [review]
LGTM except there are still the follwing two function in the mocks ([1](https://github.com/InverterNetwork/contracts/blob/sc-728-task-remove-function-mintissuancetokento-from-fm_bc_bancor/test/modules/fundingManager/bondingCurve/utils/mocks/FM_BC_Bancor_Redeeming_VirtualSupplyV1Mock.sol#L72), [2](https://github.com/InverterNetwork/contracts/blob/sc-728-task-remove-function-mintissuancetokento-from-fm_bc_bancor/test/modules/fundingManager/bondingCurve/utils/mocks/FM_BC_Restricted_Bancor_Redeeming_VirtualSupplyV1Mock.sol#L81)) and the CI is failing

**Comment by 0xNuggan** [comment]
Funnily, those functions weren't related to mintIssuanceTokenTo() :laughing:  They were intended to test the regular _mint() function. but since we are testing that through other ways, I removed it anyway. CI was failing because of address collision, let's see how it goes this time

**Comment by Zitzak** [comment]
> Funnily, those functions weren't related to mintIssuanceTokenTo() 😆 They were intended to test the regular _mint() function. but since we are testing that through other ways, I removed it anyway. CI was failing because of address collision, let's see how it goes this time

Yeah I was searching for the function name, and those popped up, and no where else. And of course you're right, they actually didn't expose any internal function related to the once you removed :D

**Review by Zitzak — APPROVED** [review]
LGTM

**Review by marvinkruse — APPROVED** [review]
lgtm!

**Pull request merged**
