### PR TITLE
[SC-633] Bug(55) TransparentProxy can't be paused

### PR DESCRIPTION
**Pull request by FHieser**
Is based on the #585
I would either wait until that PR is resolved to review this or to to look at the latest commit, as that one holds all the relevant changes

### CODE REVIEW

**Review by marvinkruse — COMMENTED** [review]
lgtm, waiting with final confirmation when other PR is merged and this one rebased 👍

**Comment by FHieser** [comment]
I think a rebase or cherry pick of the last PR is probably best to resolve the conflicts

**Comment by marvinkruse** [comment]
I believe it would be better to treat this separate from the Reverter thing, as that will only be on `dev` for now. I will change this now quickly.

**Comment by marvinkruse** [comment]
Redone in #599 as this PR was based on a branch that went to `dev` instead of `hats-fixes`

**Pull request closed without merging**
