### PR TITLE
[SC-667] (Bug119) reentrancy vulnerability in Vulnerability in PP_Streaming_v1::claimPreviouslyUnclaimable Results in Temporary Lock of Fund

### PR DESCRIPTION
**Pull request by 0xNuggan**
## What has been done
The calll to update PaymentClient.amountPaid() now happens before the transfer.

### CODE REVIEW

**Review by marvinkruse — APPROVED** [review]
lgtm!

**Review by Zitzak — APPROVED** [review]
LGTM

**Comment by Zitzak** [comment]
Hmm not sure what is happening here, it is not even compiling. @marvinkruse

**Comment by marvinkruse** [comment]
I'll check, one sec

**Comment by marvinkruse** [comment]
damn, that's an issue on `hats-fixes` directly, not sure why my CI didn't fail, probably is one of my commits. I'll fix.. :D

**Pull request merged**
