### PR TITLE
Chore: Fix compiler warnings

### PR DESCRIPTION
**Pull request by marvinkruse**
Fixed all of the compiler warnings. Such beauty:
Screenshot 2024-08-13 at 02 25 00

### CODE REVIEW

**Review by FHieser — APPROVED** [review]

**Comment by 0xNuggan** [comment]
image

**Review by 0xNuggan — APPROVED** [review]

**Comment by Zitzak** [comment]
Can this be merged, then I'll merge it into the refactor work @marvinkruse

**Comment by marvinkruse** [comment]
However you want @Zitzak either we can just merge this one and you rebase yours or I can merge this onto into your PR.

**Comment by Zitzak** [comment]
> However you want @Zitzak either we can just merge this one and you rebase yours or I can merge this onto into your PR.

@marvinkruse I think we can just merge this, as we are pressed for time

**Pull request merged**
