### PR TITLE
SC-148: Security Review - Interface lib ERC165Checker

### PR DESCRIPTION
**Pull request by FHieser**
Solves #409

### CODE REVIEW

**Review by Zitzak — DISMISSED** [review]
LGTM

**Review by Zitzak — COMMENTED** [review]
I did approve, assuming that the test that was failing was prob for the interfaces, that we fixed in the `temp_dev` branch. It seems however that a different test is failing @FHieser. The code itself looks good, but as we agreed, I should only approve when I'm okay with it being merged, which is why I removed the approval.

Update: [This fix](https://github.com/InverterNetwork/inverter-contracts/pull/414/commits/39578b4cc2a4eb40befef54f86cd838abd2719a4) should solve the CI failure related to the address collision in the BondingCurve contract

**Comment by FHieser** [comment]
Should I implement this fix in this branch? @Zitzak

**Comment by Zitzak** [comment]
Thinking about it, I think it's fine. As long as it's eventually in the `dev` branch, and works before merging into `main`
@FHieser

**Review by Zitzak — APPROVED** [review]
LGTM. The failing BondingCurve test is addresses in PR#414, which is why I'm approving despite failing CI

**Pull request merged**
