### PR TITLE
Chore: Move VotingRoleManager to authorizer extensions

### PR DESCRIPTION
**Pull request by FHieser**

### CODE REVIEW

**Comment by marvinkruse** [comment]
Did you merge the MetadataManager removal changes into this PR already or why is it in here as well?

**Comment by FHieser** [comment]
> Did you merge the MetadataManager removal changes into this PR already or why is it in here as well?

Yes exactly

**Comment by 0xNuggan** [comment]
I see the "[thing]Manager" nomenclature is still alive and healthy :rofl: I think we wanted to move away from it? Maybe something like "AUT_EXT_Voting_v1" would be better?

**Comment by FHieser** [comment]
> I see the "[thing]Manager" nomenclature is still alive and healthy 🤣 I think we wanted to move away from it? Maybe something like "AUT_EXT_Voting_v1" would be better?

Sure
I have no hard opinion on this. @marvinkruse ?

**Comment by marvinkruse** [comment]
Sorry to be nitpicking, but one thing I noticed is that you called the folder `extension`, while I think it should be `extensions` (plural), just like we use `interfaces` or `abstracts`. Otherwise I'm happy 👍

> I have no hard opinion on this. @marvinkruse?

I am not against the `Manager` naming, I still like it, but he has a point with the `AUT_EXT` part. Maybe `AUT_EXT_VotingRoles_v1`? As I think just having `Voting` is a bit ambiguous in terms of "_voting of what?_". 
(Tagging @0xNuggan as well for a quick check for opinion),

**Review by marvinkruse — CHANGES_REQUESTED** [review]
- Renaming `extension` to `extensions` (if you agree)
- Renaming of contract name according to discussion above

**Review by marvinkruse — APPROVED** [review]

**Pull request merged**
