### PR TITLE
[SC-503] Bug(H-8): Attacker may DoS KPI rewarder by filling out the staking queue

### PR DESCRIPTION
**Pull request by 0xNuggan**
## What has been done
- Added a minimum stake requirement to the stake functions. It starts out at zero, but the workflow owner can increase it if they deem it necessary
- Updated tests

### CODE REVIEW

**Review by FHieser — APPROVED** [review]

**Comment by 0xNuggan** [comment]
tagging @Zitzak  since it's high and we want 2 reviews

**Comment by Zitzak** [comment]
Just for my understanding, instead of adding a mechanism to manage the queue (as the auditors suggested) you introduced a cost to staking (a min amount) which should also deter sybil attacks. Did I get that right? @0xNuggan

**Review by Zitzak — APPROVED** [review]
LGTM

**Comment by 0xNuggan** [comment]
They suggested both options, none of them perfect. Adding a minimum stake mitigates the vector somewhat. The other solution would have required extra work and changes

**Pull request merged**
